### ISSUE TITLE
Argument 1 passed to Inspector\Configuration::setEnabled() must be of the t     ype bool

### ISSUE THREAD

**Issue by buglinjo** [inspector-apm/inspector-laravel#11]
I'm trying to install inspector in my Laravel project. I'm getting this error after running `composer require inspector-apm/inspector-laravel`

```
In Configuration.php line 174:
                                                                               
  Argument 1 passed to Inspector\Configuration::setEnabled() must be of the t  
  ype bool, null given, called in /Users/bug/Projects/new-account-api/vendor/  
  inspector-apm/inspector-laravel/src/InspectorServiceProvider.php on line 61
```

**Comment by buglinjo** [comment]
I have fixed it running:
`composer update`
`php artisan config:clear`
`composer require inspector-apm/inspector-laravel`

Please close this issue.

**Comment by ilvalerione** [comment]
Hi @buglinjo thank you for write also the solution, it is also detailed in the documentation.

**Comment by iShotFT** [comment]
A short notice on the above issue, if you're still getting the error while runing `php artisan config:clear`, a solution is removing the contents of `/bootstrap/cache`, this is because running an artisan command actually bootstraps the laravel application which will throw the error because it attempts to load Inspector as well.
