### ISSUE TITLE
Argument 1 passed to Inspector\Models\Segment::__construct() must be an   instance of Inspector\Models\Transaction, null given,

### ISSUE THREAD

**Issue by kyranb** [inspector-apm/inspector-laravel#13]
**Describe the bug**

The following error is showing when calling
```
catch{
Inspector::reportException($exception);
}
```

while inspector is installed.

```
In Segment.php line 16:

  Argument 1 passed to Inspector\Models\Segment::__construct() must be an
  instance of Inspector\Models\Transaction, null given, called in /home/ze
  ncast/releases/391/vendor/inspector-apm/inspector-php/src/Inspector.php
  on line 112
```

**Expected behavior**
The error should be caught and logged without issue.

** Versions
- inspector-apm/inspector-laravel        4.4.13
- inspector-apm/inspector-php 3.2.8
 - laravel/framework v6.18.25

**Comment by ilvalerione** [comment]
Hi @kyranb, thank you for your report.

The exception is fired by `inspector-php` package, because the `reportException` method should be called inside an active transaction. 

I released a new minor fix to this package `inspector-php: 3.2.14` so if there isn't an active transaction it starts a new one with the exception message as name. 

You simply need to upgrade your composer dependencies to get the latest version.

Anyway if you need to report that exception to Inspector consider to wrap this part of your application inside a transaction (e.g. using the WebRequestMonitoring middleware) so you'll also have a complete overview of what tasks your application execute before fires that exception.
