### ISSUE TITLE
Is this product production ready 

### ISSUE THREAD

**Issue by ravdeepsingh22** [inspector-apm/inspector-laravel#19]
**Describe the bug**
The Official website of "inspector.dev"  this tool itself has number of issues , spelling  mistakes ,  broken links . This arises questions and doubts on the reliability and quality of your product , if your website has so many issues , how would you detect the issues for your clients ?

**Comment by ilvalerione** [comment]
Hi @ravdeepsingh22  thank you for letting us know about these issues. I'm really sorry you didn't have a positive experience.

We work hard to make sure that everything is perfect, and having the good fortune to welcome new customers almost every day we have intensified efforts to improve our product and support our users, and evidently we have neglected important details in our communication.

Anyway to aswer your question about the status of the product, I can tell you that the Laravel package is monitoring more than 1000 applications from dozens of customers (Agencies, Software Houses, Freelancers, etc) around the world (USA, Australia, United Kindom, Germany, Spain, Singapore, an more). 

You can take a look of what other developers are saying about Inspector on our testimonial page: [https://inspector.dev/testimonials/](https://inspector.dev/testimonials/)

Our company is also part of one of the most important startup accelerator in Italy ([Nana Bianca](https://nanabianca.it/)) that support us to move the company forward.

We would be grateful if you would like to add more details about the problems you have encountered in order to give us the opportunity to fix them:

- Where did you encounter broken links?
- What are the problems that prevented you from trying the product?
