### ISSUE TITLE
Laravel Octane (Swoole) support

### ISSUE THREAD

**Issue by esseplore-it** [inspector-apm/inspector-laravel#22]
HTTP requests monitoring not working when using Laravel Octane (Swoole).
Similiar issue https://github.com/DataDog/dd-trace-php/issues/704.

**Comment by ilvalerione** [comment]
Hi @esseplore-it,
thank you for your report. 

To make Inspector works using Octane you simply need to manually flush data to our system.

1) Create a new middleware that extends the Inspector original `WebRequestMonitoring` middleware:

```
php artisan make:middleware InspectorFlushMiddleware
```

2) Override the `terminate` method to flush data when the request is completed:

```php
<?php

namespace App\Http\Middleware;

use Inspector\Laravel\Middleware\WebRequestMonitoring;

class InspectorFlushMiddleware extends WebRequestMonitoring
{
    public function terminate($request, $response)
    {
        parent::terminate($request, $response);

        inspector()->flush();
    }
}
```

3) Use this middleware in your App\Http\Kernel class instead of the original Inspector middleware:

```php
    /**
     * The application's route middleware groups.
     *
     * @var array
     */
    protected $middlewareGroups = [
        'web' => [
            ...,
            InspectorFlushMiddleware::class,
        ],

        'api' => [
            ...,
            InspectorFlushMiddleware::class,
        ],
    ];
```

Let me know if this fix your issue, so we can add this in the official documentation too.

**Comment by esseplore-it** [comment]
Thanks! It's working now.
But, Servers KPIs return so many hostnames. Is it correct behavior?
![image](https://user-images.githubusercontent.com/91321451/144573489-920d49a8-c8f7-4616-95b4-ecd4d02c7de4.png)

**Comment by ilvalerione** [comment]
It depends by the design of your system.

Take a look at this article, it could be helpful for this scenario:

https://inspector.dev/how-to-monitor-your-laravel-application-by-services-not-by-hostnames/
